// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { GongsimStatusDB } from '../gongsimstatus-db'
import { GongsimStatusService } from '../gongsimstatus.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-gongsimstatusstable',
  templateUrl: './gongsimstatuss-table.component.html',
  styleUrls: ['./gongsimstatuss-table.component.css'],
})
export class GongsimStatussTableComponent implements OnInit {

  // used if the component is called as a selection component of GongsimStatus instances
  selection: SelectionModel<GongsimStatusDB>;
  initialSelection = new Array<GongsimStatusDB>();

  // the data source for the table
  gongsimstatuss: GongsimStatusDB[];
  matTableDataSource: MatTableDataSource<GongsimStatusDB>


  // front repo, that will be referenced by this.gongsimstatuss
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

	// enable sorting on all fields (including pointers and reverse pointer)
	this.matTableDataSource.sortingDataAccessor = (gongsimstatusDB: GongsimStatusDB, property: string) => {
		switch (property) {
				// insertion point for specific sorting accessor
				default:
					return GongsimStatusDB[property];
		}
	}; 

	// enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
	this.matTableDataSource.filterPredicate = (gongsimstatusDB: GongsimStatusDB, filter: string) => {

		// filtering is based on finding a lower case filter into a concatenated string
		// the gongsimstatusDB properties
		let mergedContent = ""

		// insertion point for merging of fields
		mergedContent += gongsimstatusDB.Name.toLowerCase()
		mergedContent += gongsimstatusDB.CurrentCommand.toLowerCase()
		mergedContent += gongsimstatusDB.CompletionDate.toLowerCase()
		mergedContent += gongsimstatusDB.CurrentSpeedCommand.toLowerCase()
		mergedContent += gongsimstatusDB.SpeedCommandCompletionDate.toLowerCase()

		let isSelected = mergedContent.includes(filter.toLowerCase())
		return isSelected
	};

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private gongsimstatusService: GongsimStatusService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of gongsimstatus instances
    public dialogRef: MatDialogRef<GongsimStatussTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.gongsimstatusService.GongsimStatusServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getGongsimStatuss()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "CurrentCommand",
        "CompletionDate",
        "CurrentSpeedCommand",
        "SpeedCommandCompletionDate",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "CurrentCommand",
        "CompletionDate",
        "CurrentSpeedCommand",
        "SpeedCommandCompletionDate",
      ]
      this.selection = new SelectionModel<GongsimStatusDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getGongsimStatuss()
    this.matTableDataSource = new MatTableDataSource(this.gongsimstatuss)
  }

  getGongsimStatuss(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.gongsimstatuss = this.frontRepo.GongsimStatuss_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.gongsimstatuss.forEach(
            gongsimstatus => {
              let ID = this.dialogData.ID
              let revPointer = gongsimstatus[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(gongsimstatus)
              }
            }
          )
          this.selection = new SelectionModel<GongsimStatusDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.gongsimstatuss
      }
    )
  }

  // newGongsimStatus initiate a new gongsimstatus
  // create a new GongsimStatus objet
  newGongsimStatus() {
  }

  deleteGongsimStatus(gongsimstatusID: number, gongsimstatus: GongsimStatusDB) {
    // list of gongsimstatuss is truncated of gongsimstatus before the delete
    this.gongsimstatuss = this.gongsimstatuss.filter(h => h !== gongsimstatus);

    this.gongsimstatusService.deleteGongsimStatus(gongsimstatusID).subscribe(
      gongsimstatus => {
        this.gongsimstatusService.GongsimStatusServiceChanged.next("delete")
      }
    );
  }

  editGongsimStatus(gongsimstatusID: number, gongsimstatus: GongsimStatusDB) {

  }

  // display gongsimstatus in router
  displayGongsimStatusInRouter(gongsimstatusID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongsim_go-" + "gongsimstatus-display", gongsimstatusID])
  }

  // set editor outlet
  setEditorRouterOutlet(gongsimstatusID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongsim_go_editor: ["github_com_fullstack_lang_gongsim_go-" + "gongsimstatus-detail", gongsimstatusID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(gongsimstatusID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongsim_go_presentation: ["github_com_fullstack_lang_gongsim_go-" + "gongsimstatus-presentation", gongsimstatusID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.gongsimstatuss.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.gongsimstatuss.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<GongsimStatusDB>()

    // reset all initial selection of gongsimstatus that belong to gongsimstatus through Anarrayofb
    this.initialSelection.forEach(
      gongsimstatus => {
        gongsimstatus[this.dialogData.ReversePointer].Int64 = 0
        gongsimstatus[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(gongsimstatus)
      }
    )

    // from selection, set gongsimstatus that belong to gongsimstatus through Anarrayofb
    this.selection.selected.forEach(
      gongsimstatus => {
        let ID = +this.dialogData.ID
        gongsimstatus[this.dialogData.ReversePointer].Int64 = ID
        gongsimstatus[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(gongsimstatus)
      }
    )

    // update all gongsimstatus (only update selection & initial selection)
    toUpdate.forEach(
      gongsimstatus => {
        this.gongsimstatusService.updateGongsimStatus(gongsimstatus)
          .subscribe(gongsimstatus => {
            this.gongsimstatusService.GongsimStatusServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
