// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { EngineDB } from '../engine-db'
import { EngineService } from '../engine.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-engine-sorting',
  templateUrl: './engine-sorting.component.html',
  styleUrls: ['./engine-sorting.component.css']
})
export class EngineSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of Engine instances that are in the association
  associatedEngines = new Array<EngineDB>();

  constructor(
    private engineService: EngineService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of engine instances
    public dialogRef: MatDialogRef<EngineSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getEngines()
  }

  getEngines(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let engine of this.frontRepo.Engines_array) {
          let ID = this.dialogData.ID
          let revPointerID = engine[this.dialogData.ReversePointer]
          let revPointerID_Index = engine[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedEngines.push(engine)
          }
        }

        // sort associated engine according to order
        this.associatedEngines.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedEngines, event.previousIndex, event.currentIndex);

    // set the order of Engine instances
    let index = 0
    
    for (let engine of this.associatedEngines) {
      let revPointerID_Index = engine[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedEngines.forEach(
      engine => {
        this.engineService.updateEngine(engine)
          .subscribe(engine => {
            this.engineService.EngineServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
