// generated by ModelGongEnumFileTemplate
package models

// insertion point of enum utility functions
// Utility function for ControlMode
// if enum values are string, it is stored with the value
// if enum values are int, they are stored with the code of the value
func (controlmode ControlMode) ToString() (res string) {

	// migration of former implementation of enum
	switch controlmode {
	// insertion code per enum code
	case AUTONOMOUS:
		res = "Autonomous"
	case CLIENT_CONTROL:
		res = "ClientControl"
	}
	return
}

func (controlmode *ControlMode) FromString(input string) (err error) {

	switch input {
	// insertion code per enum code
	case "Autonomous":
		*controlmode = AUTONOMOUS
	case "ClientControl":
		*controlmode = CLIENT_CONTROL
	default:
		return errUnkownEnum
	}
	return
}

func (controlmode *ControlMode) FromCodeString(input string) (err error) {

	switch input {
	// insertion code per enum code
	case "AUTONOMOUS":
		*controlmode = AUTONOMOUS
	case "CLIENT_CONTROL":
		*controlmode = CLIENT_CONTROL
	default:
		return errUnkownEnum
	}
	return
}

func (controlmode *ControlMode) ToCodeString() (res string) {

	switch *controlmode {
	// insertion code per enum code
	case AUTONOMOUS:
		res = "AUTONOMOUS"
	case CLIENT_CONTROL:
		res = "CLIENT_CONTROL"
	}
	return
}

// Utility function for EngineDriverState
// if enum values are string, it is stored with the value
// if enum values are int, they are stored with the code of the value
func (enginedriverstate EngineDriverState) ToInt() (res int) {

	// migration of former implementation of enum
	switch enginedriverstate {
	// insertion code per enum code
	case COMMIT_AGENT_STATES:
		res = 0
	case CHECKOUT_AGENT_STATES:
		res = 1
	case FIRE_ONE_EVENT:
		res = 2
	case SLEEP_100_MS:
		res = 3
	case RESET_SIMULATION:
		res = 4
	case UNKOWN:
		res = 5
	}
	return
}

func (enginedriverstate *EngineDriverState) FromInt(input int) (err error) {

	switch input {
	// insertion code per enum code
	case 0:
		*enginedriverstate = COMMIT_AGENT_STATES
	case 1:
		*enginedriverstate = CHECKOUT_AGENT_STATES
	case 2:
		*enginedriverstate = FIRE_ONE_EVENT
	case 3:
		*enginedriverstate = SLEEP_100_MS
	case 4:
		*enginedriverstate = RESET_SIMULATION
	case 5:
		*enginedriverstate = UNKOWN
	default:
		return errUnkownEnum
	}
	return
}

func (enginedriverstate *EngineDriverState) FromCodeString(input string) (err error) {

	switch input {
	// insertion code per enum code
	case "COMMIT_AGENT_STATES":
		*enginedriverstate = COMMIT_AGENT_STATES
	case "CHECKOUT_AGENT_STATES":
		*enginedriverstate = CHECKOUT_AGENT_STATES
	case "FIRE_ONE_EVENT":
		*enginedriverstate = FIRE_ONE_EVENT
	case "SLEEP_100_MS":
		*enginedriverstate = SLEEP_100_MS
	case "RESET_SIMULATION":
		*enginedriverstate = RESET_SIMULATION
	case "UNKOWN":
		*enginedriverstate = UNKOWN
	default:
		return errUnkownEnum
	}
	return
}

func (enginedriverstate *EngineDriverState) ToCodeString() (res string) {

	switch *enginedriverstate {
	// insertion code per enum code
	case COMMIT_AGENT_STATES:
		res = "COMMIT_AGENT_STATES"
	case CHECKOUT_AGENT_STATES:
		res = "CHECKOUT_AGENT_STATES"
	case FIRE_ONE_EVENT:
		res = "FIRE_ONE_EVENT"
	case SLEEP_100_MS:
		res = "SLEEP_100_MS"
	case RESET_SIMULATION:
		res = "RESET_SIMULATION"
	case UNKOWN:
		res = "UNKOWN"
	}
	return
}

// Utility function for EngineRunMode
// if enum values are string, it is stored with the value
// if enum values are int, they are stored with the code of the value
func (enginerunmode EngineRunMode) ToInt() (res int) {

	// migration of former implementation of enum
	switch enginerunmode {
	// insertion code per enum code
	case RELATIVE_SPEED:
		res = 0
	case FULL_SPEED:
		res = 1
	}
	return
}

func (enginerunmode *EngineRunMode) FromInt(input int) (err error) {

	switch input {
	// insertion code per enum code
	case 0:
		*enginerunmode = RELATIVE_SPEED
	case 1:
		*enginerunmode = FULL_SPEED
	default:
		return errUnkownEnum
	}
	return
}

func (enginerunmode *EngineRunMode) FromCodeString(input string) (err error) {

	switch input {
	// insertion code per enum code
	case "RELATIVE_SPEED":
		*enginerunmode = RELATIVE_SPEED
	case "FULL_SPEED":
		*enginerunmode = FULL_SPEED
	default:
		return errUnkownEnum
	}
	return
}

func (enginerunmode *EngineRunMode) ToCodeString() (res string) {

	switch *enginerunmode {
	// insertion code per enum code
	case RELATIVE_SPEED:
		res = "RELATIVE_SPEED"
	case FULL_SPEED:
		res = "FULL_SPEED"
	}
	return
}

// Utility function for EngineState
// if enum values are string, it is stored with the value
// if enum values are int, they are stored with the code of the value
func (enginestate EngineState) ToString() (res string) {

	// migration of former implementation of enum
	switch enginestate {
	// insertion code per enum code
	case RUNNING:
		res = "RUNNING"
	case PAUSED:
		res = "PAUSED"
	case OVER:
		res = "OVER"
	}
	return
}

func (enginestate *EngineState) FromString(input string) (err error) {

	switch input {
	// insertion code per enum code
	case "RUNNING":
		*enginestate = RUNNING
	case "PAUSED":
		*enginestate = PAUSED
	case "OVER":
		*enginestate = OVER
	default:
		return errUnkownEnum
	}
	return
}

func (enginestate *EngineState) FromCodeString(input string) (err error) {

	switch input {
	// insertion code per enum code
	case "RUNNING":
		*enginestate = RUNNING
	case "PAUSED":
		*enginestate = PAUSED
	case "OVER":
		*enginestate = OVER
	default:
		return errUnkownEnum
	}
	return
}

func (enginestate *EngineState) ToCodeString() (res string) {

	switch *enginestate {
	// insertion code per enum code
	case RUNNING:
		res = "RUNNING"
	case PAUSED:
		res = "PAUSED"
	case OVER:
		res = "OVER"
	}
	return
}

// Utility function for EngineStopMode
// if enum values are string, it is stored with the value
// if enum values are int, they are stored with the code of the value
func (enginestopmode EngineStopMode) ToInt() (res int) {

	// migration of former implementation of enum
	switch enginestopmode {
	// insertion code per enum code
	case TEN_MINUTES:
		res = 0
	case STATE_CHANGED:
		res = 1
	}
	return
}

func (enginestopmode *EngineStopMode) FromInt(input int) (err error) {

	switch input {
	// insertion code per enum code
	case 0:
		*enginestopmode = TEN_MINUTES
	case 1:
		*enginestopmode = STATE_CHANGED
	default:
		return errUnkownEnum
	}
	return
}

func (enginestopmode *EngineStopMode) FromCodeString(input string) (err error) {

	switch input {
	// insertion code per enum code
	case "TEN_MINUTES":
		*enginestopmode = TEN_MINUTES
	case "STATE_CHANGED":
		*enginestopmode = STATE_CHANGED
	default:
		return errUnkownEnum
	}
	return
}

func (enginestopmode *EngineStopMode) ToCodeString() (res string) {

	switch *enginestopmode {
	// insertion code per enum code
	case TEN_MINUTES:
		res = "TEN_MINUTES"
	case STATE_CHANGED:
		res = "STATE_CHANGED"
	}
	return
}

// Utility function for GongsimCommandType
// if enum values are string, it is stored with the value
// if enum values are int, they are stored with the code of the value
func (gongsimcommandtype GongsimCommandType) ToString() (res string) {

	// migration of former implementation of enum
	switch gongsimcommandtype {
	// insertion code per enum code
	case COMMAND_PLAY:
		res = "PLAY"
	case COMMAND_PAUSE:
		res = "PAUSE"
	case COMMAND_FIRE_NEXT_EVENT:
		res = "FIRE_NEXT_EVENT"
	case COMMAND_FIRE_EVENT_TILL_STATES_CHANGE:
		res = "FIRE_EVENT_TILL_STATES_CHANGE"
	case COMMAND_RESET:
		res = "RESET"
	case COMMAND_ADVANCE_10_MIN:
		res = "ADVANCE_10_MIN"
	}
	return
}

func (gongsimcommandtype *GongsimCommandType) FromString(input string) (err error) {

	switch input {
	// insertion code per enum code
	case "PLAY":
		*gongsimcommandtype = COMMAND_PLAY
	case "PAUSE":
		*gongsimcommandtype = COMMAND_PAUSE
	case "FIRE_NEXT_EVENT":
		*gongsimcommandtype = COMMAND_FIRE_NEXT_EVENT
	case "FIRE_EVENT_TILL_STATES_CHANGE":
		*gongsimcommandtype = COMMAND_FIRE_EVENT_TILL_STATES_CHANGE
	case "RESET":
		*gongsimcommandtype = COMMAND_RESET
	case "ADVANCE_10_MIN":
		*gongsimcommandtype = COMMAND_ADVANCE_10_MIN
	default:
		return errUnkownEnum
	}
	return
}

func (gongsimcommandtype *GongsimCommandType) FromCodeString(input string) (err error) {

	switch input {
	// insertion code per enum code
	case "COMMAND_PLAY":
		*gongsimcommandtype = COMMAND_PLAY
	case "COMMAND_PAUSE":
		*gongsimcommandtype = COMMAND_PAUSE
	case "COMMAND_FIRE_NEXT_EVENT":
		*gongsimcommandtype = COMMAND_FIRE_NEXT_EVENT
	case "COMMAND_FIRE_EVENT_TILL_STATES_CHANGE":
		*gongsimcommandtype = COMMAND_FIRE_EVENT_TILL_STATES_CHANGE
	case "COMMAND_RESET":
		*gongsimcommandtype = COMMAND_RESET
	case "COMMAND_ADVANCE_10_MIN":
		*gongsimcommandtype = COMMAND_ADVANCE_10_MIN
	default:
		return errUnkownEnum
	}
	return
}

func (gongsimcommandtype *GongsimCommandType) ToCodeString() (res string) {

	switch *gongsimcommandtype {
	// insertion code per enum code
	case COMMAND_PLAY:
		res = "COMMAND_PLAY"
	case COMMAND_PAUSE:
		res = "COMMAND_PAUSE"
	case COMMAND_FIRE_NEXT_EVENT:
		res = "COMMAND_FIRE_NEXT_EVENT"
	case COMMAND_FIRE_EVENT_TILL_STATES_CHANGE:
		res = "COMMAND_FIRE_EVENT_TILL_STATES_CHANGE"
	case COMMAND_RESET:
		res = "COMMAND_RESET"
	case COMMAND_ADVANCE_10_MIN:
		res = "COMMAND_ADVANCE_10_MIN"
	}
	return
}

// Utility function for SpeedCommandType
// if enum values are string, it is stored with the value
// if enum values are int, they are stored with the code of the value
func (speedcommandtype SpeedCommandType) ToString() (res string) {

	// migration of former implementation of enum
	switch speedcommandtype {
	// insertion code per enum code
	case COMMAND_INCREASE_SPEED_100_PERCENTS:
		res = "INCREASE_SPEED_100_PERCENTS"
	case COMMAND_DECREASE_SPEED_50_PERCENTS:
		res = "COMMAND_DECREASE_SPEED_50_PERCENTS "
	case COMMAND_SPEED_STEADY:
		res = "COMMAND_SPEED_STEADY"
	}
	return
}

func (speedcommandtype *SpeedCommandType) FromString(input string) (err error) {

	switch input {
	// insertion code per enum code
	case "INCREASE_SPEED_100_PERCENTS":
		*speedcommandtype = COMMAND_INCREASE_SPEED_100_PERCENTS
	case "COMMAND_DECREASE_SPEED_50_PERCENTS ":
		*speedcommandtype = COMMAND_DECREASE_SPEED_50_PERCENTS
	case "COMMAND_SPEED_STEADY":
		*speedcommandtype = COMMAND_SPEED_STEADY
	default:
		return errUnkownEnum
	}
	return
}

func (speedcommandtype *SpeedCommandType) FromCodeString(input string) (err error) {

	switch input {
	// insertion code per enum code
	case "COMMAND_INCREASE_SPEED_100_PERCENTS":
		*speedcommandtype = COMMAND_INCREASE_SPEED_100_PERCENTS
	case "COMMAND_DECREASE_SPEED_50_PERCENTS":
		*speedcommandtype = COMMAND_DECREASE_SPEED_50_PERCENTS
	case "COMMAND_SPEED_STEADY":
		*speedcommandtype = COMMAND_SPEED_STEADY
	default:
		return errUnkownEnum
	}
	return
}

func (speedcommandtype *SpeedCommandType) ToCodeString() (res string) {

	switch *speedcommandtype {
	// insertion code per enum code
	case COMMAND_INCREASE_SPEED_100_PERCENTS:
		res = "COMMAND_INCREASE_SPEED_100_PERCENTS"
	case COMMAND_DECREASE_SPEED_50_PERCENTS:
		res = "COMMAND_DECREASE_SPEED_50_PERCENTS"
	case COMMAND_SPEED_STEADY:
		res = "COMMAND_SPEED_STEADY"
	}
	return
}

// Last line of the template
