// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { UpdateStateDB } from '../updatestate-db'
import { UpdateStateService } from '../updatestate.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-updatestate-sorting',
  templateUrl: './updatestate-sorting.component.html',
  styleUrls: ['./updatestate-sorting.component.css']
})
export class UpdateStateSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of UpdateState instances that are in the association
  associatedUpdateStates = new Array<UpdateStateDB>();

  constructor(
    private updatestateService: UpdateStateService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of updatestate instances
    public dialogRef: MatDialogRef<UpdateStateSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getUpdateStates()
  }

  getUpdateStates(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let updatestate of this.frontRepo.UpdateStates_array) {
          let ID = this.dialogData.ID
          let revPointerID = updatestate[this.dialogData.ReversePointer]
          let revPointerID_Index = updatestate[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedUpdateStates.push(updatestate)
          }
        }

        // sort associated updatestate according to order
        this.associatedUpdateStates.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedUpdateStates, event.previousIndex, event.currentIndex);

    // set the order of UpdateState instances
    let index = 0
    
    for (let updatestate of this.associatedUpdateStates) {
      let revPointerID_Index = updatestate[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedUpdateStates.forEach(
      updatestate => {
        this.updatestateService.updateUpdateState(updatestate)
          .subscribe(updatestate => {
            this.updatestateService.UpdateStateServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
