// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { UpdateStateDB } from '../updatestate-db'
import { UpdateStateService } from '../updatestate.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-updatestatestable',
  templateUrl: './updatestates-table.component.html',
  styleUrls: ['./updatestates-table.component.css'],
})
export class UpdateStatesTableComponent implements OnInit {

  // used if the component is called as a selection component of UpdateState instances
  selection: SelectionModel<UpdateStateDB>;
  initialSelection = new Array<UpdateStateDB>();

  // the data source for the table
  updatestates: UpdateStateDB[];
  matTableDataSource: MatTableDataSource<UpdateStateDB>


  // front repo, that will be referenced by this.updatestates
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

	// enable sorting on all fields (including pointers and reverse pointer)
	this.matTableDataSource.sortingDataAccessor = (updatestateDB: UpdateStateDB, property: string) => {
		switch (property) {
				// insertion point for specific sorting accessor
			case 'Name':
				return updatestateDB.Name;

			case 'Duration':
				return updatestateDB.Duration;

			case 'Period':
				return updatestateDB.Period;

				default:
					return UpdateStateDB[property];
		}
	}; 

	// enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
	this.matTableDataSource.filterPredicate = (updatestateDB: UpdateStateDB, filter: string) => {

		// filtering is based on finding a lower case filter into a concatenated string
		// the updatestateDB properties
		let mergedContent = ""

		// insertion point for merging of fields
		mergedContent += updatestateDB.Name.toLowerCase()

		let isSelected = mergedContent.includes(filter.toLowerCase())
		return isSelected
	};

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private updatestateService: UpdateStateService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of updatestate instances
    public dialogRef: MatDialogRef<UpdateStatesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.updatestateService.UpdateStateServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getUpdateStates()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Duration",
        "Period",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Duration",
        "Period",
      ]
      this.selection = new SelectionModel<UpdateStateDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getUpdateStates()
    this.matTableDataSource = new MatTableDataSource(this.updatestates)
  }

  getUpdateStates(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.updatestates = this.frontRepo.UpdateStates_array;

        // insertion point for variables Recoveries
        // compute strings for durations
        for (let updatestate of this.updatestates) {
          updatestate.Duration_string =
            Math.floor(updatestate.Duration / (3600 * 1000 * 1000 * 1000)) + "H " +
            Math.floor(updatestate.Duration % (3600 * 1000 * 1000 * 1000) / (60 * 1000 * 1000 * 1000)) + "M " +
            updatestate.Duration % (60 * 1000 * 1000 * 1000) / (1000 * 1000 * 1000) + "S"
        }
        // compute strings for durations
        for (let updatestate of this.updatestates) {
          updatestate.Period_string =
            Math.floor(updatestate.Period / (3600 * 1000 * 1000 * 1000)) + "H " +
            Math.floor(updatestate.Period % (3600 * 1000 * 1000 * 1000) / (60 * 1000 * 1000 * 1000)) + "M " +
            updatestate.Period % (60 * 1000 * 1000 * 1000) / (1000 * 1000 * 1000) + "S"
        }

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.updatestates.forEach(
            updatestate => {
              let ID = this.dialogData.ID
              let revPointer = updatestate[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(updatestate)
              }
            }
          )
          this.selection = new SelectionModel<UpdateStateDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.updatestates
      }
    )
  }

  // newUpdateState initiate a new updatestate
  // create a new UpdateState objet
  newUpdateState() {
  }

  deleteUpdateState(updatestateID: number, updatestate: UpdateStateDB) {
    // list of updatestates is truncated of updatestate before the delete
    this.updatestates = this.updatestates.filter(h => h !== updatestate);

    this.updatestateService.deleteUpdateState(updatestateID).subscribe(
      updatestate => {
        this.updatestateService.UpdateStateServiceChanged.next("delete")
      }
    );
  }

  editUpdateState(updatestateID: number, updatestate: UpdateStateDB) {

  }

  // display updatestate in router
  displayUpdateStateInRouter(updatestateID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongsim_go-" + "updatestate-display", updatestateID])
  }

  // set editor outlet
  setEditorRouterOutlet(updatestateID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongsim_go_editor: ["github_com_fullstack_lang_gongsim_go-" + "updatestate-detail", updatestateID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(updatestateID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongsim_go_presentation: ["github_com_fullstack_lang_gongsim_go-" + "updatestate-presentation", updatestateID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.updatestates.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.updatestates.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<UpdateStateDB>()

    // reset all initial selection of updatestate that belong to updatestate through Anarrayofb
    this.initialSelection.forEach(
      updatestate => {
        updatestate[this.dialogData.ReversePointer].Int64 = 0
        updatestate[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(updatestate)
      }
    )

    // from selection, set updatestate that belong to updatestate through Anarrayofb
    this.selection.selected.forEach(
      updatestate => {
        let ID = +this.dialogData.ID
        updatestate[this.dialogData.ReversePointer].Int64 = ID
        updatestate[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(updatestate)
      }
    )

    // update all updatestate (only update selection & initial selection)
    toUpdate.forEach(
      updatestate => {
        this.updatestateService.updateUpdateState(updatestate)
          .subscribe(updatestate => {
            this.updatestateService.UpdateStateServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
