// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"github.com/fullstack-lang/gongsim/go/models"
	"github.com/fullstack-lang/gongsim/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __DummyAgent__dummysDeclaration__ models.DummyAgent
var __DummyAgent_time__dummyDeclaration time.Duration

// An DummyAgentID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getDummyAgent updateDummyAgent deleteDummyAgent
type DummyAgentID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// DummyAgentInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postDummyAgent updateDummyAgent
type DummyAgentInput struct {
	// The DummyAgent to submit or modify
	// in: body
	DummyAgent *orm.DummyAgentAPI
}

// GetDummyAgents
//
// swagger:route GET /dummyagents dummyagents getDummyAgents
//
// # Get all dummyagents
//
// Responses:
// default: genericError
//
//	200: dummyagentDBResponse
func (controller *Controller) GetDummyAgents(c *gin.Context) {

	// source slice
	var dummyagentDBs []orm.DummyAgentDB

	values := c.Request.URL.Query()
	stackPath := ""
	if len(values) == 1 {
		value := values["GONG__StackPath"]
		if len(value) == 1 {
			stackPath = value[0]
			log.Println("GetDummyAgents", "GONG__StackPath", stackPath)
		}
	}
	backRepo := controller.Map_BackRepos[stackPath]
	db := backRepo.BackRepoDummyAgent.GetDB()

	query := db.Find(&dummyagentDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	dummyagentAPIs := make([]orm.DummyAgentAPI, 0)

	// for each dummyagent, update fields from the database nullable fields
	for idx := range dummyagentDBs {
		dummyagentDB := &dummyagentDBs[idx]
		_ = dummyagentDB
		var dummyagentAPI orm.DummyAgentAPI

		// insertion point for updating fields
		dummyagentAPI.ID = dummyagentDB.ID
		dummyagentDB.CopyBasicFieldsToDummyAgent(&dummyagentAPI.DummyAgent)
		dummyagentAPI.DummyAgentPointersEnconding = dummyagentDB.DummyAgentPointersEnconding
		dummyagentAPIs = append(dummyagentAPIs, dummyagentAPI)
	}

	c.JSON(http.StatusOK, dummyagentAPIs)
}

// PostDummyAgent
//
// swagger:route POST /dummyagents dummyagents postDummyAgent
//
// Creates a dummyagent
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func (controller *Controller) PostDummyAgent(c *gin.Context) {

	values := c.Request.URL.Query()
	stackPath := ""
	if len(values) == 1 {
		value := values["GONG__StackPath"]
		if len(value) == 1 {
			stackPath = value[0]
			log.Println("PostDummyAgents", "GONG__StackPath", stackPath)
		}
	}
	backRepo := controller.Map_BackRepos[stackPath]
	db := backRepo.BackRepoDummyAgent.GetDB()

	// Validate input
	var input orm.DummyAgentAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create dummyagent
	dummyagentDB := orm.DummyAgentDB{}
	dummyagentDB.DummyAgentPointersEnconding = input.DummyAgentPointersEnconding
	dummyagentDB.CopyBasicFieldsFromDummyAgent(&input.DummyAgent)

	query := db.Create(&dummyagentDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	backRepo.BackRepoDummyAgent.CheckoutPhaseOneInstance(&dummyagentDB)
	dummyagent := (*backRepo.BackRepoDummyAgent.Map_DummyAgentDBID_DummyAgentPtr)[dummyagentDB.ID]

	if dummyagent != nil {
		models.AfterCreateFromFront(backRepo.GetStage(), dummyagent)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	backRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, dummyagentDB)
}

// GetDummyAgent
//
// swagger:route GET /dummyagents/{ID} dummyagents getDummyAgent
//
// Gets the details for a dummyagent.
//
// Responses:
// default: genericError
//
//	200: dummyagentDBResponse
func (controller *Controller) GetDummyAgent(c *gin.Context) {

	values := c.Request.URL.Query()
	stackPath := ""
	if len(values) == 1 {
		value := values["GONG__StackPath"]
		if len(value) == 1 {
			stackPath = value[0]
			log.Println("GetDummyAgent", "GONG__StackPath", stackPath)
		}
	}
	backRepo := controller.Map_BackRepos[stackPath]
	db := backRepo.BackRepoDummyAgent.GetDB()

	// Get dummyagentDB in DB
	var dummyagentDB orm.DummyAgentDB
	if err := db.First(&dummyagentDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var dummyagentAPI orm.DummyAgentAPI
	dummyagentAPI.ID = dummyagentDB.ID
	dummyagentAPI.DummyAgentPointersEnconding = dummyagentDB.DummyAgentPointersEnconding
	dummyagentDB.CopyBasicFieldsToDummyAgent(&dummyagentAPI.DummyAgent)

	c.JSON(http.StatusOK, dummyagentAPI)
}

// UpdateDummyAgent
//
// swagger:route PATCH /dummyagents/{ID} dummyagents updateDummyAgent
//
// # Update a dummyagent
//
// Responses:
// default: genericError
//
//	200: dummyagentDBResponse
func (controller *Controller) UpdateDummyAgent(c *gin.Context) {

	values := c.Request.URL.Query()
	stackPath := ""
	if len(values) == 1 {
		value := values["GONG__StackPath"]
		if len(value) == 1 {
			stackPath = value[0]
			log.Println("UpdateDummyAgent", "GONG__StackPath", stackPath)
		}
	}
	backRepo := controller.Map_BackRepos[stackPath]
	db := backRepo.BackRepoDummyAgent.GetDB()

	// Validate input
	var input orm.DummyAgentAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Get model if exist
	var dummyagentDB orm.DummyAgentDB

	// fetch the dummyagent
	query := db.First(&dummyagentDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// update
	dummyagentDB.CopyBasicFieldsFromDummyAgent(&input.DummyAgent)
	dummyagentDB.DummyAgentPointersEnconding = input.DummyAgentPointersEnconding

	query = db.Model(&dummyagentDB).Updates(dummyagentDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	dummyagentNew := new(models.DummyAgent)
	dummyagentDB.CopyBasicFieldsToDummyAgent(dummyagentNew)

	// get stage instance from DB instance, and call callback function
	dummyagentOld := (*backRepo.BackRepoDummyAgent.Map_DummyAgentDBID_DummyAgentPtr)[dummyagentDB.ID]
	if dummyagentOld != nil {
		models.AfterUpdateFromFront(backRepo.GetStage(), dummyagentOld, dummyagentNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	backRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the dummyagentDB
	c.JSON(http.StatusOK, dummyagentDB)
}

// DeleteDummyAgent
//
// swagger:route DELETE /dummyagents/{ID} dummyagents deleteDummyAgent
//
// # Delete a dummyagent
//
// default: genericError
//
//	200: dummyagentDBResponse
func (controller *Controller) DeleteDummyAgent(c *gin.Context) {

	values := c.Request.URL.Query()
	stackPath := ""
	if len(values) == 1 {
		value := values["GONG__StackPath"]
		if len(value) == 1 {
			stackPath = value[0]
			log.Println("DeleteDummyAgent", "GONG__StackPath", stackPath)
		}
	}
	backRepo := controller.Map_BackRepos[stackPath]
	db := backRepo.BackRepoDummyAgent.GetDB()

	// Get model if exist
	var dummyagentDB orm.DummyAgentDB
	if err := db.First(&dummyagentDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&dummyagentDB)

	// get an instance (not staged) from DB instance, and call callback function
	dummyagentDeleted := new(models.DummyAgent)
	dummyagentDB.CopyBasicFieldsToDummyAgent(dummyagentDeleted)

	// get stage instance from DB instance, and call callback function
	dummyagentStaged := (*backRepo.BackRepoDummyAgent.Map_DummyAgentDBID_DummyAgentPtr)[dummyagentDB.ID]
	if dummyagentStaged != nil {
		models.AfterDeleteFromFront(backRepo.GetStage(), dummyagentStaged, dummyagentDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	backRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
