// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"github.com/fullstack-lang/gongsim/go/models"
	"github.com/fullstack-lang/gongsim/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __GongsimCommand__dummysDeclaration__ models.GongsimCommand
var __GongsimCommand_time__dummyDeclaration time.Duration

// An GongsimCommandID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getGongsimCommand updateGongsimCommand deleteGongsimCommand
type GongsimCommandID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// GongsimCommandInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postGongsimCommand updateGongsimCommand
type GongsimCommandInput struct {
	// The GongsimCommand to submit or modify
	// in: body
	GongsimCommand *orm.GongsimCommandAPI
}

// GetGongsimCommands
//
// swagger:route GET /gongsimcommands gongsimcommands getGongsimCommands
//
// # Get all gongsimcommands
//
// Responses:
// default: genericError
//
//	200: gongsimcommandDBResponse
func GetGongsimCommands(c *gin.Context) {
	db := orm.BackRepo.BackRepoGongsimCommand.GetDB()

	// source slice
	var gongsimcommandDBs []orm.GongsimCommandDB
	query := db.Find(&gongsimcommandDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	gongsimcommandAPIs := make([]orm.GongsimCommandAPI, 0)

	// for each gongsimcommand, update fields from the database nullable fields
	for idx := range gongsimcommandDBs {
		gongsimcommandDB := &gongsimcommandDBs[idx]
		_ = gongsimcommandDB
		var gongsimcommandAPI orm.GongsimCommandAPI

		// insertion point for updating fields
		gongsimcommandAPI.ID = gongsimcommandDB.ID
		gongsimcommandDB.CopyBasicFieldsToGongsimCommand(&gongsimcommandAPI.GongsimCommand)
		gongsimcommandAPI.GongsimCommandPointersEnconding = gongsimcommandDB.GongsimCommandPointersEnconding
		gongsimcommandAPIs = append(gongsimcommandAPIs, gongsimcommandAPI)
	}

	c.JSON(http.StatusOK, gongsimcommandAPIs)
}

// PostGongsimCommand
//
// swagger:route POST /gongsimcommands gongsimcommands postGongsimCommand
//
// Creates a gongsimcommand
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func PostGongsimCommand(c *gin.Context) {
	db := orm.BackRepo.BackRepoGongsimCommand.GetDB()

	// Validate input
	var input orm.GongsimCommandAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create gongsimcommand
	gongsimcommandDB := orm.GongsimCommandDB{}
	gongsimcommandDB.GongsimCommandPointersEnconding = input.GongsimCommandPointersEnconding
	gongsimcommandDB.CopyBasicFieldsFromGongsimCommand(&input.GongsimCommand)

	query := db.Create(&gongsimcommandDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	orm.BackRepo.BackRepoGongsimCommand.CheckoutPhaseOneInstance(&gongsimcommandDB)
	gongsimcommand := (*orm.BackRepo.BackRepoGongsimCommand.Map_GongsimCommandDBID_GongsimCommandPtr)[gongsimcommandDB.ID]

	if gongsimcommand != nil {
		models.AfterCreateFromFront(&models.Stage, gongsimcommand)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gongsimcommandDB)
}

// GetGongsimCommand
//
// swagger:route GET /gongsimcommands/{ID} gongsimcommands getGongsimCommand
//
// Gets the details for a gongsimcommand.
//
// Responses:
// default: genericError
//
//	200: gongsimcommandDBResponse
func GetGongsimCommand(c *gin.Context) {
	db := orm.BackRepo.BackRepoGongsimCommand.GetDB()

	// Get gongsimcommandDB in DB
	var gongsimcommandDB orm.GongsimCommandDB
	if err := db.First(&gongsimcommandDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var gongsimcommandAPI orm.GongsimCommandAPI
	gongsimcommandAPI.ID = gongsimcommandDB.ID
	gongsimcommandAPI.GongsimCommandPointersEnconding = gongsimcommandDB.GongsimCommandPointersEnconding
	gongsimcommandDB.CopyBasicFieldsToGongsimCommand(&gongsimcommandAPI.GongsimCommand)

	c.JSON(http.StatusOK, gongsimcommandAPI)
}

// UpdateGongsimCommand
//
// swagger:route PATCH /gongsimcommands/{ID} gongsimcommands updateGongsimCommand
//
// # Update a gongsimcommand
//
// Responses:
// default: genericError
//
//	200: gongsimcommandDBResponse
func UpdateGongsimCommand(c *gin.Context) {
	db := orm.BackRepo.BackRepoGongsimCommand.GetDB()

	// Get model if exist
	var gongsimcommandDB orm.GongsimCommandDB

	// fetch the gongsimcommand
	query := db.First(&gongsimcommandDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.GongsimCommandAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	gongsimcommandDB.CopyBasicFieldsFromGongsimCommand(&input.GongsimCommand)
	gongsimcommandDB.GongsimCommandPointersEnconding = input.GongsimCommandPointersEnconding

	query = db.Model(&gongsimcommandDB).Updates(gongsimcommandDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	gongsimcommandNew := new(models.GongsimCommand)
	gongsimcommandDB.CopyBasicFieldsToGongsimCommand(gongsimcommandNew)

	// get stage instance from DB instance, and call callback function
	gongsimcommandOld := (*orm.BackRepo.BackRepoGongsimCommand.Map_GongsimCommandDBID_GongsimCommandPtr)[gongsimcommandDB.ID]
	if gongsimcommandOld != nil {
		models.AfterUpdateFromFront(&models.Stage, gongsimcommandOld, gongsimcommandNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the gongsimcommandDB
	c.JSON(http.StatusOK, gongsimcommandDB)
}

// DeleteGongsimCommand
//
// swagger:route DELETE /gongsimcommands/{ID} gongsimcommands deleteGongsimCommand
//
// # Delete a gongsimcommand
//
// default: genericError
//
//	200: gongsimcommandDBResponse
func DeleteGongsimCommand(c *gin.Context) {
	db := orm.BackRepo.BackRepoGongsimCommand.GetDB()

	// Get model if exist
	var gongsimcommandDB orm.GongsimCommandDB
	if err := db.First(&gongsimcommandDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&gongsimcommandDB)

	// get an instance (not staged) from DB instance, and call callback function
	gongsimcommandDeleted := new(models.GongsimCommand)
	gongsimcommandDB.CopyBasicFieldsToGongsimCommand(gongsimcommandDeleted)

	// get stage instance from DB instance, and call callback function
	gongsimcommandStaged := (*orm.BackRepo.BackRepoGongsimCommand.Map_GongsimCommandDBID_GongsimCommandPtr)[gongsimcommandDB.ID]
	if gongsimcommandStaged != nil {
		models.AfterDeleteFromFront(&models.Stage, gongsimcommandStaged, gongsimcommandDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
