// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { EventDB } from '../event-db'
import { EventService } from '../event.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-events-table',
  templateUrl: './events-table.component.html',
  styleUrls: ['./events-table.component.css'],
})
export class EventsTableComponent implements OnInit {

  // used if the component is called as a selection component of Event instances
  selection: SelectionModel<EventDB>;
  initialSelection = new Array<EventDB>();

  // the data source for the table
  events: EventDB[];
  matTableDataSource: MatTableDataSource<EventDB>


  // front repo, that will be referenced by this.events
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private eventService: EventService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of event instances
    public dialogRef: MatDialogRef<EventsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.eventService.EventServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getEvents()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Duration",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Duration",
      ]
      this.selection = new SelectionModel<EventDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getEvents()
    this.matTableDataSource = new MatTableDataSource(this.events)
  }

  getEvents(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo
        console.log("front repo pull returned")

        this.events = this.frontRepo.Events_array;

        // insertion point for variables Recoveries
        // compute strings for durations
        for (let event of this.events) {
          event.Duration_string =
            Math.floor(event.Duration / (3600 * 1000 * 1000 * 1000)) + "H " +
            Math.floor(event.Duration % (3600 * 1000 * 1000 * 1000) / (60 * 1000 * 1000 * 1000)) + "M " +
            event.Duration % (60 * 1000 * 1000 * 1000) / (1000 * 1000 * 1000) + "S"
        }

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.events.forEach(
            event => {
              let ID = this.dialogData.ID
              let revPointer = event[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(event)
              }
            }
          )
          this.selection = new SelectionModel<EventDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.events
      }
    )
  }

  // newEvent initiate a new event
  // create a new Event objet
  newEvent() {
  }

  deleteEvent(eventID: number, event: EventDB) {
    // list of events is truncated of event before the delete
    this.events = this.events.filter(h => h !== event);

    this.eventService.deleteEvent(eventID).subscribe(
      event => {
        this.eventService.EventServiceChanged.next("delete")

        console.log("event deleted")
      }
    );
  }

  editEvent(eventID: number, event: EventDB) {

  }

  // display event in router
  displayEventInRouter(eventID: number) {
    this.router.navigate(["event-display", eventID])
  }

  // set editor outlet
  setEditorRouterOutlet(eventID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["event-detail", eventID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(eventID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["event-presentation", eventID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.events.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.events.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<EventDB>()

    // reset all initial selection of event that belong to event through Anarrayofb
    this.initialSelection.forEach(
      event => {
        event[this.dialogData.ReversePointer].Int64 = 0
        event[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(event)
      }
    )

    // from selection, set event that belong to event through Anarrayofb
    this.selection.selected.forEach(
      event => {
        console.log("selection ID " + event.ID)
        let ID = +this.dialogData.ID
        event[this.dialogData.ReversePointer].Int64 = ID
        event[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(event)
      }
    )

    // update all event (only update selection & initial selection)
    toUpdate.forEach(
      event => {
        this.eventService.updateEvent(event)
          .subscribe(event => {
            this.eventService.EventServiceChanged.next("update")
            console.log("event saved")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
