// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { DummyAgentDB } from './dummyagent-db';

@Injectable({
  providedIn: 'root'
})
export class DummyAgentService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  DummyAgentServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private dummyagentsUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gongsim/go/v1/dummyagents';

  constructor(
    private http: HttpClient
  ) { }

  /** GET dummyagents from the server */
  getDummyAgents(): Observable<DummyAgentDB[]> {
    return this.http.get<DummyAgentDB[]>(this.dummyagentsUrl)
      .pipe(
        tap(_ => this.log('fetched dummyagents')),
        catchError(this.handleError<DummyAgentDB[]>('getDummyAgents', []))
      );
  }

  /** GET dummyagent by id. Will 404 if id not found */
  getDummyAgent(id: number): Observable<DummyAgentDB> {
    const url = `${this.dummyagentsUrl}/${id}`;
    return this.http.get<DummyAgentDB>(url).pipe(
      tap(_ => this.log(`fetched dummyagent id=${id}`)),
      catchError(this.handleError<DummyAgentDB>(`getDummyAgent id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new dummyagent to the server */
  postDummyAgent(dummyagentdb: DummyAgentDB): Observable<DummyAgentDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    dummyagentdb.Engine = {}

		return this.http.post<DummyAgentDB>(this.dummyagentsUrl, dummyagentdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted dummyagentdb id=${dummyagentdb.ID}`)
			}),
			catchError(this.handleError<DummyAgentDB>('postDummyAgent'))
		);
  }

  /** DELETE: delete the dummyagentdb from the server */
  deleteDummyAgent(dummyagentdb: DummyAgentDB | number): Observable<DummyAgentDB> {
    const id = typeof dummyagentdb === 'number' ? dummyagentdb : dummyagentdb.ID;
    const url = `${this.dummyagentsUrl}/${id}`;

    return this.http.delete<DummyAgentDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted dummyagentdb id=${id}`)),
      catchError(this.handleError<DummyAgentDB>('deleteDummyAgent'))
    );
  }

  /** PUT: update the dummyagentdb on the server */
  updateDummyAgent(dummyagentdb: DummyAgentDB): Observable<DummyAgentDB> {
    const id = typeof dummyagentdb === 'number' ? dummyagentdb : dummyagentdb.ID;
    const url = `${this.dummyagentsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    dummyagentdb.Engine = {}

    return this.http.put(url, dummyagentdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated dummyagentdb id=${dummyagentdb.ID}`)
      }),
      catchError(this.handleError<DummyAgentDB>('updateDummyAgent'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
