// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { DummyAgentDB } from './dummyagent-db';
import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class DummyAgentService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  DummyAgentServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private dummyagentsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.dummyagentsUrl = origin + '/api/github.com/fullstack-lang/gongsim/go/v1/dummyagents';
  }

  /** GET dummyagents from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyAgentDB[]> {
    return this.getDummyAgents(GONG__StackPath, frontRepo)
  }
  getDummyAgents(GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyAgentDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<DummyAgentDB[]>(this.dummyagentsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched dummyagents')),
        catchError(this.handleError<DummyAgentDB[]>('getDummyAgents', []))
      );
  }

  /** GET dummyagent by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyAgentDB> {
    return this.getDummyAgent(id, GONG__StackPath, frontRepo)
  }
  getDummyAgent(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyAgentDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.dummyagentsUrl}/${id}`;
    return this.http.get<DummyAgentDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched dummyagent id=${id}`)),
      catchError(this.handleError<DummyAgentDB>(`getDummyAgent id=${id}`))
    );
  }

  /** POST: add a new dummyagent to the server */
  post(dummyagentdb: DummyAgentDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyAgentDB> {
    return this.postDummyAgent(dummyagentdb, GONG__StackPath, frontRepo)
  }
  postDummyAgent(dummyagentdb: DummyAgentDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyAgentDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<DummyAgentDB>(this.dummyagentsUrl, dummyagentdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted dummyagentdb id=${dummyagentdb.ID}`)
      }),
      catchError(this.handleError<DummyAgentDB>('postDummyAgent'))
    );
  }

  /** DELETE: delete the dummyagentdb from the server */
  delete(dummyagentdb: DummyAgentDB | number, GONG__StackPath: string): Observable<DummyAgentDB> {
    return this.deleteDummyAgent(dummyagentdb, GONG__StackPath)
  }
  deleteDummyAgent(dummyagentdb: DummyAgentDB | number, GONG__StackPath: string): Observable<DummyAgentDB> {
    const id = typeof dummyagentdb === 'number' ? dummyagentdb : dummyagentdb.ID;
    const url = `${this.dummyagentsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<DummyAgentDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted dummyagentdb id=${id}`)),
      catchError(this.handleError<DummyAgentDB>('deleteDummyAgent'))
    );
  }

  /** PUT: update the dummyagentdb on the server */
  update(dummyagentdb: DummyAgentDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyAgentDB> {
    return this.updateDummyAgent(dummyagentdb, GONG__StackPath, frontRepo)
  }
  updateDummyAgent(dummyagentdb: DummyAgentDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyAgentDB> {
    const id = typeof dummyagentdb === 'number' ? dummyagentdb : dummyagentdb.ID;
    const url = `${this.dummyagentsUrl}/${id}`;

    // insertion point for reset of pointers (to avoid circular JSON)
	// and encoding of pointers

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<DummyAgentDB>(url, dummyagentdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated dummyagentdb id=${dummyagentdb.ID}`)
      }),
      catchError(this.handleError<DummyAgentDB>('updateDummyAgent'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in DummyAgentService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("DummyAgentService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
