// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { EngineDB } from './engine-db'
import { Engine, CopyEngineToEngineDB } from './engine'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class EngineService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  EngineServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private enginesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.enginesUrl = origin + '/api/github.com/fullstack-lang/gongsim/go/v1/engines';
  }

  /** GET engines from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<EngineDB[]> {
    return this.getEngines(GONG__StackPath, frontRepo)
  }
  getEngines(GONG__StackPath: string, frontRepo: FrontRepo): Observable<EngineDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<EngineDB[]>(this.enginesUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<EngineDB[]>('getEngines', []))
      );
  }

  /** GET engine by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<EngineDB> {
    return this.getEngine(id, GONG__StackPath, frontRepo)
  }
  getEngine(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<EngineDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.enginesUrl}/${id}`;
    return this.http.get<EngineDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched engine id=${id}`)),
      catchError(this.handleError<EngineDB>(`getEngine id=${id}`))
    );
  }

  // postFront copy engine to a version with encoded pointers and post to the back
  postFront(engine: Engine, GONG__StackPath: string): Observable<EngineDB> {
    let engineDB = new EngineDB
    CopyEngineToEngineDB(engine, engineDB)
    const id = typeof engineDB === 'number' ? engineDB : engineDB.ID
    const url = `${this.enginesUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<EngineDB>(url, engineDB, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<EngineDB>('postEngine'))
    );
  }
  
  /** POST: add a new engine to the server */
  post(enginedb: EngineDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<EngineDB> {
    return this.postEngine(enginedb, GONG__StackPath, frontRepo)
  }
  postEngine(enginedb: EngineDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<EngineDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<EngineDB>(this.enginesUrl, enginedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted enginedb id=${enginedb.ID}`)
      }),
      catchError(this.handleError<EngineDB>('postEngine'))
    );
  }

  /** DELETE: delete the enginedb from the server */
  delete(enginedb: EngineDB | number, GONG__StackPath: string): Observable<EngineDB> {
    return this.deleteEngine(enginedb, GONG__StackPath)
  }
  deleteEngine(enginedb: EngineDB | number, GONG__StackPath: string): Observable<EngineDB> {
    const id = typeof enginedb === 'number' ? enginedb : enginedb.ID;
    const url = `${this.enginesUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<EngineDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted enginedb id=${id}`)),
      catchError(this.handleError<EngineDB>('deleteEngine'))
    );
  }

  // updateFront copy engine to a version with encoded pointers and update to the back
  updateFront(engine: Engine, GONG__StackPath: string): Observable<EngineDB> {
    let engineDB = new EngineDB
    CopyEngineToEngineDB(engine, engineDB)
    const id = typeof engineDB === 'number' ? engineDB : engineDB.ID
    const url = `${this.enginesUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<EngineDB>(url, engineDB, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<EngineDB>('updateEngine'))
    );
  }

  /** PUT: update the enginedb on the server */
  update(enginedb: EngineDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<EngineDB> {
    return this.updateEngine(enginedb, GONG__StackPath, frontRepo)
  }
  updateEngine(enginedb: EngineDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<EngineDB> {
    const id = typeof enginedb === 'number' ? enginedb : enginedb.ID;
    const url = `${this.enginesUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<EngineDB>(url, enginedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated enginedb id=${enginedb.ID}`)
      }),
      catchError(this.handleError<EngineDB>('updateEngine'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in EngineService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("EngineService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
