// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { EventDB } from './event-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class EventService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  EventServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private eventsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.eventsUrl = origin + '/api/github.com/fullstack-lang/gongsim/go/v1/events';
  }

  /** GET events from the server */
  getEvents(GONG__StackPath: string): Observable<EventDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<EventDB[]>(this.eventsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched events')),
        catchError(this.handleError<EventDB[]>('getEvents', []))
      );
  }

  /** GET event by id. Will 404 if id not found */
  getEvent(id: number, GONG__StackPath: string): Observable<EventDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.eventsUrl}/${id}`;
    return this.http.get<EventDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched event id=${id}`)),
      catchError(this.handleError<EventDB>(`getEvent id=${id}`))
    );
  }

  /** POST: add a new event to the server */
  postEvent(eventdb: EventDB, GONG__StackPath: string): Observable<EventDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<EventDB>(this.eventsUrl, eventdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted eventdb id=${eventdb.ID}`)
      }),
      catchError(this.handleError<EventDB>('postEvent'))
    );
  }

  /** DELETE: delete the eventdb from the server */
  deleteEvent(eventdb: EventDB | number, GONG__StackPath: string): Observable<EventDB> {
    const id = typeof eventdb === 'number' ? eventdb : eventdb.ID;
    const url = `${this.eventsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<EventDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted eventdb id=${id}`)),
      catchError(this.handleError<EventDB>('deleteEvent'))
    );
  }

  /** PUT: update the eventdb on the server */
  updateEvent(eventdb: EventDB, GONG__StackPath: string): Observable<EventDB> {
    const id = typeof eventdb === 'number' ? eventdb : eventdb.ID;
    const url = `${this.eventsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<EventDB>(url, eventdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated eventdb id=${eventdb.ID}`)
      }),
      catchError(this.handleError<EventDB>('updateEvent'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in EventService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("EventService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
