// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { GongsimCommandDB } from './gongsimcommand-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class GongsimCommandService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  GongsimCommandServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private gongsimcommandsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.gongsimcommandsUrl = origin + '/api/github.com/fullstack-lang/gongsim/go/v1/gongsimcommands';
  }

  /** GET gongsimcommands from the server */
  getGongsimCommands(GONG__StackPath: string = ""): Observable<GongsimCommandDB[]> {

	let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<GongsimCommandDB[]>(this.gongsimcommandsUrl, { params: params })
      .pipe(
        tap(_ => this.log('fetched gongsimcommands')),
        catchError(this.handleError<GongsimCommandDB[]>('getGongsimCommands', []))
      );
  }

  /** GET gongsimcommand by id. Will 404 if id not found */
  getGongsimCommand(id: number): Observable<GongsimCommandDB> {
    const url = `${this.gongsimcommandsUrl}/${id}`;
    return this.http.get<GongsimCommandDB>(url).pipe(
      tap(_ => this.log(`fetched gongsimcommand id=${id}`)),
      catchError(this.handleError<GongsimCommandDB>(`getGongsimCommand id=${id}`))
    );
  }

  /** POST: add a new gongsimcommand to the server */
  postGongsimCommand(gongsimcommanddb: GongsimCommandDB, GONG__StackPath: string): Observable<GongsimCommandDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

	return this.http.post<GongsimCommandDB>(this.gongsimcommandsUrl, gongsimcommanddb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted gongsimcommanddb id=${gongsimcommanddb.ID}`)
      }),
      catchError(this.handleError<GongsimCommandDB>('postGongsimCommand'))
    );
  }

  /** DELETE: delete the gongsimcommanddb from the server */
  deleteGongsimCommand(gongsimcommanddb: GongsimCommandDB | number, GONG__StackPath: string): Observable<GongsimCommandDB> {
    const id = typeof gongsimcommanddb === 'number' ? gongsimcommanddb : gongsimcommanddb.ID;
    const url = `${this.gongsimcommandsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<GongsimCommandDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted gongsimcommanddb id=${id}`)),
      catchError(this.handleError<GongsimCommandDB>('deleteGongsimCommand'))
    );
  }

  /** PUT: update the gongsimcommanddb on the server */
  updateGongsimCommand(gongsimcommanddb: GongsimCommandDB, GONG__StackPath: string): Observable<GongsimCommandDB> {
    const id = typeof gongsimcommanddb === 'number' ? gongsimcommanddb : gongsimcommanddb.ID;
    const url = `${this.gongsimcommandsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<GongsimCommandDB>(url, gongsimcommanddb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated gongsimcommanddb id=${gongsimcommanddb.ID}`)
      }),
      catchError(this.handleError<GongsimCommandDB>('updateGongsimCommand'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
