// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { GongsimStatusAPI } from './gongsimstatus-api'
import { GongsimStatus, CopyGongsimStatusToGongsimStatusAPI } from './gongsimstatus'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class GongsimStatusService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  GongsimStatusServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private gongsimstatussUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.gongsimstatussUrl = origin + '/api/github.com/fullstack-lang/gongsim/go/v1/gongsimstatuss';
  }

  /** GET gongsimstatuss from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<GongsimStatusAPI[]> {
    return this.getGongsimStatuss(GONG__StackPath, frontRepo)
  }
  getGongsimStatuss(GONG__StackPath: string, frontRepo: FrontRepo): Observable<GongsimStatusAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<GongsimStatusAPI[]>(this.gongsimstatussUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<GongsimStatusAPI[]>('getGongsimStatuss', []))
      );
  }

  /** GET gongsimstatus by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<GongsimStatusAPI> {
    return this.getGongsimStatus(id, GONG__StackPath, frontRepo)
  }
  getGongsimStatus(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<GongsimStatusAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.gongsimstatussUrl}/${id}`;
    return this.http.get<GongsimStatusAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched gongsimstatus id=${id}`)),
      catchError(this.handleError<GongsimStatusAPI>(`getGongsimStatus id=${id}`))
    );
  }

  // postFront copy gongsimstatus to a version with encoded pointers and post to the back
  postFront(gongsimstatus: GongsimStatus, GONG__StackPath: string): Observable<GongsimStatusAPI> {
    let gongsimstatusAPI = new GongsimStatusAPI
    CopyGongsimStatusToGongsimStatusAPI(gongsimstatus, gongsimstatusAPI)
    const id = typeof gongsimstatusAPI === 'number' ? gongsimstatusAPI : gongsimstatusAPI.ID
    const url = `${this.gongsimstatussUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<GongsimStatusAPI>(url, gongsimstatusAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<GongsimStatusAPI>('postGongsimStatus'))
    );
  }
  
  /** POST: add a new gongsimstatus to the server */
  post(gongsimstatusdb: GongsimStatusAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<GongsimStatusAPI> {
    return this.postGongsimStatus(gongsimstatusdb, GONG__StackPath, frontRepo)
  }
  postGongsimStatus(gongsimstatusdb: GongsimStatusAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<GongsimStatusAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<GongsimStatusAPI>(this.gongsimstatussUrl, gongsimstatusdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted gongsimstatusdb id=${gongsimstatusdb.ID}`)
      }),
      catchError(this.handleError<GongsimStatusAPI>('postGongsimStatus'))
    );
  }

  /** DELETE: delete the gongsimstatusdb from the server */
  delete(gongsimstatusdb: GongsimStatusAPI | number, GONG__StackPath: string): Observable<GongsimStatusAPI> {
    return this.deleteGongsimStatus(gongsimstatusdb, GONG__StackPath)
  }
  deleteGongsimStatus(gongsimstatusdb: GongsimStatusAPI | number, GONG__StackPath: string): Observable<GongsimStatusAPI> {
    const id = typeof gongsimstatusdb === 'number' ? gongsimstatusdb : gongsimstatusdb.ID;
    const url = `${this.gongsimstatussUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<GongsimStatusAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted gongsimstatusdb id=${id}`)),
      catchError(this.handleError<GongsimStatusAPI>('deleteGongsimStatus'))
    );
  }

  // updateFront copy gongsimstatus to a version with encoded pointers and update to the back
  updateFront(gongsimstatus: GongsimStatus, GONG__StackPath: string): Observable<GongsimStatusAPI> {
    let gongsimstatusAPI = new GongsimStatusAPI
    CopyGongsimStatusToGongsimStatusAPI(gongsimstatus, gongsimstatusAPI)
    const id = typeof gongsimstatusAPI === 'number' ? gongsimstatusAPI : gongsimstatusAPI.ID
    const url = `${this.gongsimstatussUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<GongsimStatusAPI>(url, gongsimstatusAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<GongsimStatusAPI>('updateGongsimStatus'))
    );
  }

  /** PUT: update the gongsimstatusdb on the server */
  update(gongsimstatusdb: GongsimStatusAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<GongsimStatusAPI> {
    return this.updateGongsimStatus(gongsimstatusdb, GONG__StackPath, frontRepo)
  }
  updateGongsimStatus(gongsimstatusdb: GongsimStatusAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<GongsimStatusAPI> {
    const id = typeof gongsimstatusdb === 'number' ? gongsimstatusdb : gongsimstatusdb.ID;
    const url = `${this.gongsimstatussUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<GongsimStatusAPI>(url, gongsimstatusdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated gongsimstatusdb id=${gongsimstatusdb.ID}`)
      }),
      catchError(this.handleError<GongsimStatusAPI>('updateGongsimStatus'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in GongsimStatusService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("GongsimStatusService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
