// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { DummyAgentDB } from '../dummyagent-db'
import { DummyAgentService } from '../dummyagent.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-dummyagents-table',
  templateUrl: './dummyagents-table.component.html',
  styleUrls: ['./dummyagents-table.component.css'],
})
export class DummyAgentsTableComponent implements OnInit {

  // used if the component is called as a selection component of DummyAgent instances
  selection: SelectionModel<DummyAgentDB>;
  initialSelection = new Array<DummyAgentDB>();

  // the data source for the table
  dummyagents: DummyAgentDB[];
  matTableDataSource: MatTableDataSource<DummyAgentDB>


  // front repo, that will be referenced by this.dummyagents
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private dummyagentService: DummyAgentService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of dummyagent instances
    public dialogRef: MatDialogRef<DummyAgentsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
    // this is for routerLink on same component when only queryParameter changes
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };

    // observable for changes in structs
    this.dummyagentService.DummyAgentServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getDummyAgents()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "TechName",
        "Engine",
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "TechName",
        "Engine",
        "Name",
      ]
      this.selection = new SelectionModel<DummyAgentDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getDummyAgents()
    this.matTableDataSource = new MatTableDataSource(this.dummyagents)
  }

  getDummyAgents(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo
        console.log("front repo pull returned")

        this.dummyagents = this.frontRepo.DummyAgents_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.dummyagents.forEach(
            dummyagent => {
              let ID = this.dialogData.ID
              let revPointer = dummyagent[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(dummyagent)
              }
            }
          )
          this.selection = new SelectionModel<DummyAgentDB>(allowMultiSelect, this.initialSelection);
        }

		// update the mat table data source
        this.matTableDataSource.data = this.dummyagents
      }
    )
  }

  // newDummyAgent initiate a new dummyagent
  // create a new DummyAgent objet
  newDummyAgent() {
  }

  deleteDummyAgent(dummyagentID: number, dummyagent: DummyAgentDB) {
    // list of dummyagents is truncated of dummyagent before the delete
    this.dummyagents = this.dummyagents.filter(h => h !== dummyagent);

    this.dummyagentService.deleteDummyAgent(dummyagentID).subscribe(
      dummyagent => {
        this.dummyagentService.DummyAgentServiceChanged.next("delete")

        console.log("dummyagent deleted")
      }
    );
  }

  editDummyAgent(dummyagentID: number, dummyagent: DummyAgentDB) {

  }

  // display dummyagent in router
  displayDummyAgentInRouter(dummyagentID: number) {
    this.router.navigate(["dummyagent-display", dummyagentID])
  }

  // set editor outlet
  setEditorRouterOutlet(dummyagentID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["dummyagent-detail", dummyagentID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(dummyagentID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["dummyagent-presentation", dummyagentID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.dummyagents.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.dummyagents.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<DummyAgentDB>()

    // reset all initial selection of dummyagent that belong to dummyagent through Anarrayofb
    this.initialSelection.forEach(
      dummyagent => {
        dummyagent[this.dialogData.ReversePointer].Int64 = 0
        dummyagent[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(dummyagent)
      }
    )

    // from selection, set dummyagent that belong to dummyagent through Anarrayofb
    this.selection.selected.forEach(
      dummyagent => {
        console.log("selection ID " + dummyagent.ID)
        let ID = +this.dialogData.ID
        dummyagent[this.dialogData.ReversePointer].Int64 = ID
        dummyagent[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(dummyagent)
      }
    )

    // update all dummyagent (only update selection & initial selection)
    toUpdate.forEach(
      dummyagent => {
        this.dummyagentService.updateDummyAgent(dummyagent)
          .subscribe(dummyagent => {
            this.dummyagentService.DummyAgentServiceChanged.next("update")
            console.log("dummyagent saved")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
