// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { DummyAgentDB } from '../dummyagent-db'
import { DummyAgentService } from '../dummyagent.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-dummyagentstable',
  templateUrl: './dummyagents-table.component.html',
  styleUrls: ['./dummyagents-table.component.css'],
})
export class DummyAgentsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of DummyAgent instances
  selection: SelectionModel<DummyAgentDB>;
  initialSelection = new Array<DummyAgentDB>();

  // the data source for the table
  dummyagents: DummyAgentDB[];
  matTableDataSource: MatTableDataSource<DummyAgentDB>

  // front repo, that will be referenced by this.dummyagents
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (dummyagentDB: DummyAgentDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'TechName':
          return dummyagentDB.TechName;

        case 'Engine':
          return (dummyagentDB.Engine ? dummyagentDB.Engine.Name : '');

        case 'Name':
          return dummyagentDB.Name;

        default:
          return DummyAgentDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (dummyagentDB: DummyAgentDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the dummyagentDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += dummyagentDB.TechName.toLowerCase()
      if (dummyagentDB.Engine) {
        mergedContent += dummyagentDB.Engine.Name.toLowerCase()
      }
      mergedContent += dummyagentDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private dummyagentService: DummyAgentService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of dummyagent instances
    public dialogRef: MatDialogRef<DummyAgentsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.dummyagentService.DummyAgentServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getDummyAgents()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "TechName",
        "Engine",
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "TechName",
        "Engine",
        "Name",
      ]
      this.selection = new SelectionModel<DummyAgentDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getDummyAgents()
    this.matTableDataSource = new MatTableDataSource(this.dummyagents)
  }

  getDummyAgents(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.dummyagents = this.frontRepo.DummyAgents_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.dummyagents.forEach(
            dummyagent => {
              let ID = this.dialogData.ID
              let revPointer = dummyagent[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(dummyagent)
              }
            }
          )
          this.selection = new SelectionModel<DummyAgentDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let dummyagent = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(dummyagent)
            }
          }
          this.selection = new SelectionModel<DummyAgentDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.dummyagents
      }
    )
  }

  // newDummyAgent initiate a new dummyagent
  // create a new DummyAgent objet
  newDummyAgent() {
  }

  deleteDummyAgent(dummyagentID: number, dummyagent: DummyAgentDB) {
    // list of dummyagents is truncated of dummyagent before the delete
    this.dummyagents = this.dummyagents.filter(h => h !== dummyagent);

    this.dummyagentService.deleteDummyAgent(dummyagentID).subscribe(
      dummyagent => {
        this.dummyagentService.DummyAgentServiceChanged.next("delete")
      }
    );
  }

  editDummyAgent(dummyagentID: number, dummyagent: DummyAgentDB) {

  }

  // display dummyagent in router
  displayDummyAgentInRouter(dummyagentID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongsim_go-" + "dummyagent-display", dummyagentID])
  }

  // set editor outlet
  setEditorRouterOutlet(dummyagentID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongsim_go_editor: ["github_com_fullstack_lang_gongsim_go-" + "dummyagent-detail", dummyagentID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(dummyagentID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongsim_go_presentation: ["github_com_fullstack_lang_gongsim_go-" + "dummyagent-presentation", dummyagentID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.dummyagents.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.dummyagents.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<DummyAgentDB>()

      // reset all initial selection of dummyagent that belong to dummyagent
      this.initialSelection.forEach(
        dummyagent => {
          dummyagent[this.dialogData.ReversePointer].Int64 = 0
          dummyagent[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(dummyagent)
        }
      )

      // from selection, set dummyagent that belong to dummyagent
      this.selection.selected.forEach(
        dummyagent => {
          let ID = +this.dialogData.ID
          dummyagent[this.dialogData.ReversePointer].Int64 = ID
          dummyagent[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(dummyagent)
        }
      )

      // update all dummyagent (only update selection & initial selection)
      toUpdate.forEach(
        dummyagent => {
          this.dummyagentService.updateDummyAgent(dummyagent)
            .subscribe(dummyagent => {
              this.dummyagentService.DummyAgentServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedDummyAgent = new Set<number>()
      for (let dummyagent of this.initialSelection) {
        if (this.selection.selected.includes(dummyagent)) {
          // console.log("dummyagent " + dummyagent.Name + " is still selected")
        } else {
          console.log("dummyagent " + dummyagent.Name + " has been unselected")
          unselectedDummyAgent.add(dummyagent.ID)
          console.log("is unselected " + unselectedDummyAgent.has(dummyagent.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let dummyagent = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedDummyAgent.has(dummyagent.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          dummyagent => {
            if (!this.initialSelection.includes(dummyagent)) {
              // console.log("dummyagent " + dummyagent.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + dummyagent.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = dummyagent.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("dummyagent " + dummyagent.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<DummyAgentDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
